#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'bit bootloader' --class openeuler --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-e23c76ae-b06d-4a6e-ad42-46b8eedfd7d3' {
	insmod gzio
	insmod part_gpt
	insmod ext2
	set root='hd0,msdos1'

	echo 'Loading bit bootloader ...'
	multiboot --quirk-modules-after-kernel /bootloader.elf
}
